version: '3.9'

services:
  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NotificationDB;User Id=sa;Password=StrongPassword123;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_URLS=http://*:6565
    networks:
      - backend
    ports:
      - "6565:6565"
    volumes:
      - video-zips:/app/zips

volumes:
  video-zips:
    external: true
    name: my_shared_zips 

networks:
  backend:
    external: true
